### ISSUE TITLE
Fix race condition resulting in duplicate payments

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/legacy-payment-processor#12]
Root cause

The issue is in Legacy Payment Processor

What happens in Legacy Payment Processor

Read the “challenge.notification.update” events.

Check if the challenge is a V5 Task and is completed.

Query Database to see if a payment record exists for the challenge

If no, create a payment

If yes, do nothing.

Problem

Sometimes 2 “challenge.notification.events” are generated for the challenge in quick succession.

Both execute the Steps 2 and Step 3 execute in parallel, leading the code to find no existing payment causing the same challenge being processed twice.

Solution

Wrap that read/write in a transaction. That way if one process reads, sees the payment has not been made, then writes it would be guaranteed to succeed. If another process comes in and tries to start the same transaction it would block until the first finished and see the payment was already made.

The create payment logic is already in a transaction. We need to bring in the select statement in the same transaction too.
legacy-payment-processor/processorService.js at develop · topcoder-platform/legacy-payment-processor 
Additionally, we may consider adding a unique constraint in db for user_id, challenge_id, and payment_type_id condition.

Note, if the legacy payment processor isn’t issuing direct queries to the DB and is instead going through an API, we could add an API specifically to issue a payment and it would use a transaction like I described above.

**Comment by SathyaJayabal** [comment]
Verified a v5 task on dev. Payments are getting created only once.

Unable to verify a challenge payment in dev due to this issue:
https://github.com/topcoder-platform/legacy-challenge-resource-processor/issues/30

To verify payments in prod, we will access to a project with an active billing account.

**Comment by SathyaJayabal** [comment]
This issue is observed in production again. 
https://topcoder.atlassian.net/browse/PLAT-147?focusedCommentId=16571

**Comment by SathyaJayabal** [comment]
This is verified on prod.
Only one payment was added even though multiple events were generated. 
<img width="1016" alt="Screenshot 2022-03-03 at 2 38 39 PM" src="https://user-images.githubusercontent.com/58783823/156533344-0d72ff95-ea04-45f0-ab22-43871bf5e2b7.png">
![image (44)](https://user-images.githubusercontent.com/58783823/156533378-cd7f5fe9-5d8e-4050-a986-8a171ec758c7.png)
<img width="974" alt="Screenshot 2022-03-03 at 2 37 33 PM" src="https://user-images.githubusercontent.com/58783823/156533402-dbf80768-3fca-4379-a74c-dedc80f98b76.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1029" alt="Screenshot 2022-03-07 at 11 27 32 AM" src="https://user-images.githubusercontent.com/58783823/156976344-db73b110-1604-4550-8857-82156a16df1f.png">
